# Generated by Django 5.0.3 on 2024-05-14 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voting.comment')),
                ('comments_reports', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.reportoncomment')),
                ('projects_reports', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.reportonproject')),
                ('votes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voting.vote')),
            ],
        ),
    ]
