# Generated by Django 5.0.3 on 2024-05-21 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_analyticdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalyticData',
        ),
    ]
