# Generated by Django 5.0.3 on 2024-03-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_remove_vote_user_userchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='choice_text',
            field=models.CharField(choices=[('Approve', 'Approve'), ('Disapprove', 'Disapprove')], default='Approve', max_length=200),
        ),
    ]
