# Generated by Django 5.0.3 on 2024-03-28 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment',
        ),
    ]
