# Generated by Django 5.0.3 on 2024-04-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_rename_comment_comment_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='district',
            field=models.CharField(choices=[('Galician District', 'Galician District'), ('Frankivskyi District', 'Frankivskyi District'), ('Lychakivskyi District', 'Lychakivskyi District'), ('Shevchenkivskyi District', 'Shevchenkivskyi District'), ('Sykhivskyi District', 'Sykhivskyi District'), ('Zaliznychnyi District', 'Zaliznychnyi District')], default='Galician District', max_length=50),
        ),
    ]
