# Generated by Django 5.0.3 on 2024-04-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagestorage',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_profile_picture.png', upload_to='images/'),
        ),
    ]
