# Generated by Django 5.0.3 on 2024-04-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='district',
            field=models.CharField(choices=[('Galician District', 'Galician District'), ('Frankivskyi District', 'Frankivskyi District'), ('Lychakivskyi District', 'Lychakivskyi District'), ('Shevchenkivskyi District', 'Shevchenkivskyi District'), ('Sykhivskyi District', 'Sykhivskyi District'), ('Zaliznychnyi District', 'Zaliznychnyi District')], default='Galician District', max_length=50),
        ),
    ]
